[deps]
ArviZ = "131c737c-5715-5e2e-ad31-c244f01c1dc7"
CmdStan = "593b3428-ca2f-500c-ae53-031589ec8ddd"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
PlutoStaticHTML = "359b1769-a58e-495b-9770-312e911026ad"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SampleChains = "754583d1-7fc4-4dab-93b5-5eaca5c9622e"
SampleChainsDynamicHMC = "6d9fd711-e8b2-4778-9c70-c1dfb499d4c4"
Soss = "8ce77f84-9b61-11e8-39ff-d17a774bf41c"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
ArviZ = "0.6"
CmdStan = "6.0"
DimensionalData = "0.20"
Distributions = "0.25"
Documenter = "0.27"
MCMCChains = "5.0"
PlutoStaticHTML = "4.0.5, 5"
PlutoUI = "0.7"
PyCall = "1.0"
PyPlot = "2.0"
SampleChains = "0.5"
SampleChainsDynamicHMC = "0.3.4"
SimplePosets = "< 0.1.7"
Soss = "0.20"
Turing = "0.21"
