[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
ArviZ = "131c737c-5715-5e2e-ad31-c244f01c1dc7"
ArviZExampleData = "2f96bb34-afd9-46ae-bcd0-9b2d4372fe3c"
ArviZPythonPlots = "4a6e88f0-2c8e-11ee-0601-e94153f0eada"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
EvoTrees = "f6006082-12f8-11e9-0c9c-0d5d367ab1e5"
InferenceObjects = "b5cf5a8d-e756-4ee3-b014-01d49d192c00"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCDiagnosticTools = "be115224-59cd-429b-ad48-344e309966f0"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJIteration = "614be32b-d00c-4edb-bd02-1eb411ab5e55"
PSIS = "ce719bf2-d5d0-4fb9-925d-10a81b42ad04"
PlutoStaticHTML = "359b1769-a58e-495b-9770-312e911026ad"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PosteriorStats = "7f36be82-ad55-44ba-a5c0-b8b5480d7aa5"
StanSample = "c1514b29-d3a0-5178-b312-660c88baa699"
StatisticalMeasures = "a19d573c-0a75-4610-95b3-7071388c7541"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
AlgebraOfGraphics = "0.6.13, 0.7, 0.8, 0.9, 0.10"
ArviZ = "0.12.0"
ArviZExampleData = "0.2"
ArviZPythonPlots = "0.1.7"
CairoMakie = "0.10, 0.11, 0.12, 0.13, 0.15"
DataFrames = "1.4"
DimensionalData = "0.27, 0.28, 0.29"
Distributions = "0.25.81"
Documenter = "1"
Downloads = "1"
EvoTrees = "0.14.8, 0.15, 0.16, 0.17"
InferenceObjects = "0.4"
MCMCDiagnosticTools = "0.3.4"
MLJBase = "1"
MLJIteration = "0.6"
PSIS = "0.9.1"
PlutoStaticHTML = "4.0.5, 5, 6, 7"
PlutoUI = "0.7"
PosteriorStats = "0.2.2"
StanSample = "7.0.1"
StatisticalMeasures = "0.1.1, 0.2"
Statistics = "1"
StatsBase = "0.33.7, 0.34"
Turing = "0.24.1, 0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37"
