[deps]
ArviZ = "131c737c-5715-5e2e-ad31-c244f01c1dc7"
CmdStan = "593b3428-ca2f-500c-ae53-031589ec8ddd"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Soss = "8ce77f84-9b61-11e8-39ff-d17a774bf41c"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
MCMCChains = "0.3.15, 0.4.2, 1.0"
